# Generated by Django 6.1 on 2026-09-05 18:33

import django.db.models.deletion
import django_fsm
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_factura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrden',
            fields=[
                ('idOrden', models.IntegerField(blank=True, db_index=True)),
                ('nombreProducto', models.CharField(blank=True, db_column='nombreProducto', max_length=150, null=True)),
                ('fechaCreacion', models.DateField(blank=True, editable=False)),
                ('fechaEntregaEstimada', models.DateField(blank=True, null=True)),
                ('instrucciones', models.CharField(max_length=1000)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precioUnitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prioridad', models.CharField(choices=[('Normal', 'Normal'), ('Urgente', 'Urgente')], default='Normal', max_length=10)),
                ('estado', django_fsm.FSMField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Retrasado', 'Retrasado')], default='Pendiente', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idCliente', models.ForeignKey(blank=True, db_column='idCliente', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administrador.cliente')),
                ('idProducto', models.ForeignKey(blank=True, db_column='idProducto', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administrador.producto')),
            ],
            options={
                'verbose_name': 'historical orden',
                'verbose_name_plural': 'historical ordens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
