# Generated by Django 6.1 on 2026-09-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_historicalorden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'managed': False},
        ),
    ]
