# Generated by Django 6.1 on 2026-09-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionTarea',
        ),
        migrations.DeleteModel(
            name='Incidencia',
        ),
        migrations.DeleteModel(
            name='Operario',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
