# Generated by Django 6.1 on 2026-09-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cotizacion_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
