# Generated by Django 6.1 on 2026-09-05 18:33

import django.db.models.deletion
import django_fsm
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_produccion_producto_delete_ordenproduccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduccion',
            fields=[
                ('idProduccion', models.IntegerField(blank=True, db_index=True)),
                ('idOrden', models.IntegerField(blank=True, db_column='idOrden', null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidadRequerida', models.IntegerField()),
                ('fechaInicio', models.DateField()),
                ('fechaEstimadaFin', models.DateField()),
                ('fechaRealFin', models.DateField(blank=True, null=True)),
                ('estado', django_fsm.FSMField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado'), ('Detenido', 'Detenido'), ('Retrasado', 'Retrasado')], default='Pendiente', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idProducto', models.ForeignKey(blank=True, db_column='idProducto', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='produccion.producto')),
            ],
            options={
                'verbose_name': 'historical produccion',
                'verbose_name_plural': 'historical produccions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
