# Generated by Django 6.1 on 2026-09-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_historicalproduccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('idOrdenProduccion', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('cliente', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField(default=0)),
                ('fechaInicio', models.DateField()),
                ('fechaEntrega', models.DateField()),
                ('fechaFinReal', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('Normal', 'Normal'), ('Urgente', 'Urgente')], default='Normal', max_length=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado'), ('Atrasada', 'Atrasada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ordenes_produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('idPrenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('categoria', models.CharField(max_length=20)),
                ('tallas', models.CharField(max_length=100)),
                ('tiempoMinutos', models.IntegerField()),
                ('stockObjetivo', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'prendas',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicalproduccion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproduccion',
            name='idProducto',
        ),
        migrations.DeleteModel(
            name='Produccion',
        ),
        migrations.DeleteModel(
            name='HistoricalProduccion',
        ),
    ]
